import '../styles/globals.css'
import'../styles/imports.css';

import '../styles/dashboard/CalendarStyles.css';
import '../styles/dashboard/CalendarTheme.css';

import { AuthProvider} from '../contexts/AuthContext'

import { Raleway } from 'next/font/google'
import localFont from 'next/font/local'
import Head from 'next/head';

const myFont = localFont({ src: '../assets/fonts/bernadette.ttf' })

const raleway = Raleway({
  weight: '400',
  subsets: ['latin'],
})



export default function MyApp({ Component, pageProps }) {
    // Use the layout defined at the page level, if available
  const getLayout = Component.getLayout || ((page) => page)

  return getLayout(
    <AuthProvider>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <container className={raleway.className}>
        <Component {...pageProps} />
      </container>
    </AuthProvider>
    
  )
}